name: Deploy to docker-hub

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout/Clone the repository
          uses: actions/checkout@v3
        
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push the image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/ci-cd-pipeline:latest

        - name: Verify the image
          run: docker pull ${{ secrets.DOCKER_USERNAME }}/ci-cd-pipeline:latest

        - name: Deploy to ec2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                echo "Deploying..."
                sudo docker stop ci-cd-pipeline || true
                sudo docker rm ci-cd-pipeline || true
                sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/ci-cd-pipeline:latest || true
                sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ci-cd-pipeline:latest
                sudo docker run -d -p 3000:3000 --name ci-cd-pipeline ${{ secrets.DOCKER_USERNAME }}/ci-cd-pipeline:latest
                echo "Deployed!"