name: Linting & Formatting

on:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout/Clone repository
              uses: actions/checkout@v3
            
            - name: Set up node
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
            
            - name: Install dependencies
              run: npm install

            - name: Lint with Biome
              run: npm run format-and-lint:fix